mercadonapp/__init__.py
from flask import Flask, render_template

"""
Define the application and fetch the configuration settings
"""

app = Flask(__name__)
app.config.from_object('config')

"""
ErrorHandlers for 404 and 500.
"""


@app.errorhandler(404)
def not_found(e):
    return render_template(
        'errors/404.html',
        error=e,
        title='Oupsi, un truc cloche !'
    )


@app.errorhandler(500)
def internal_error(e):
    return render_template(
        'errors/500.html',
        error=e,
        title='Problème serveur'
    )


"""
Get the routing
"""

from mercadonapp.views import home
from mercadonapp.views import catalog

app.register_blueprint(home.mod)
app.register_blueprint(catalog.mod)

"""
Initialize the database
"""

from mercadonapp.database import init_db

init_db()

mercadonapp/views/catalog.py
from flask import Blueprint, render_template
from mercadonapp import internal_error
from mercadonapp.database import get_categories, fetch_articles


mod = Blueprint('catalog', __name__)

"""
Catalog page routing and variables
"""

@mod.route('/catalogue', methods=['GET'])
def catalog():
    try:
        return render_template(
            'catalog.html',
            title='Catalogue',
            categories=get_categories(),
            articles=fetch_articles()
        )
    except RuntimeError as e:
        return internal_error(e)

mercadonapp/views/home.py
from flask import Blueprint, render_template
from mercadonapp import internal_error
from mercadonapp.database import get_categories

mod = Blueprint('home', __name__)


"""
Homepage routing and variables
"""

@mod.route('/', methods=['GET'])
def home():
    try:
        return render_template(
            'home.html',
            title='Mercadona - Plus de 100 promotions',
            categories=get_categories()
        )
    except RuntimeError as e:
        return internal_error(e)

mercadonapp/templates/_layout.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/app.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/fonts.css') }}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='img/header/favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/header/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/header/favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='img/header/favicon/site.webmanifest') }}">
    <link rel="mask-icon" href="{{ url_for('static', filename='img/header/favicon/safari-pinned-tab.svg') }}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <title>{{ title }}</title>
</head>
<body>
    {% include 'include/header.html' %}
    <div class="page page-{{ pageTemplate }}">
        {% block body %}{% endblock %}
    </div>
    {% include 'include/footer.html' %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>
</html>

mercadonapp/templates/catalog.html
{% extends '_layout.html' %}

{% set pageTemplate = 'catalog' %}

{% block body %}
    <div class="filter">
        <div class="filter-breadcrumb lazyslow-left">
            <div aria-label="Breadcrumb" class="breadcrumb">
                <div class="breadcrumb-display">
                    <a>Catalogue</a>
                </div>
            </div>
        </div>
        <div class="filter-options">
            <div class="checkbox lazyslow-left">
                <label class="checkbox-filter" for="promotion">
                    <a class="checkbox-promotion">
                        <p>Promos</p>
                        <input type="checkbox" class="reset" id="promotion" value="promotion">
                    </a>
                </label>
                <label class="checkbox-filter" for="cold">
                    <a class="checkbox-cold">
                        <p>Frais</p>
                        <input type="checkbox" class="reset" id="cold" value="cold">
                    </a>
                </label>
                <label class="checkbox-filter" for="frozen">
                    <a class="checkbox-frozen">
                        <p>Surgelé</p>
                        <input type="checkbox" class="reset" id="frozen" value="frozen">
                    </a>
                </label>
                <label class="checkbox-filter" for="bio">
                    <a class="checkbox-bio">
                        <p>Bio</p>
                        <input type="checkbox" class="reset" id="bio" value="bio">
                    </a>
                </label>
            </div>
            <label for="sort-selection" class="sort lazyslow-right">
                <select id="sort-selection" class="sort-selection">
                    <option value="default">Tri par défaut</option>
                    <option value="ascending-price">Prix croissant</option>
                    <option value="descending-price">Prix décroissant</option>
                </select>
            </label>
        </div>
    </div>
    <div class="catalog lazyslow-down">
        {% for article in articles %}
            <div class="article" id="{{ article.product }}" data-name="{{ article.brand }}" data-category="Catalogue {% for category in article.categories %}{{ category }}{% endfor %} {% for subcategory in article.subcategories %}{{ subcategory }}{% endfor %}" data-filters="{% for filter in article.filters %} {{ filter.classe }} {% endfor %}" data-price="{% if article.promotion_percentage is not none %} {{ article.promoted_price }} {% else %} {{ article.price }} {% endif %}">
                {% if article.promotion_start is not none %}
                    <span class="article-promotion K2D-paragraph">{{ article.promotion_start }} - {{ article.promotion_end }}</span>
                {% endif %}
                <img class="article-img" src="{{ article.image }}" alt="">
                <div class="article-badges">
                    {% if article.filters is not none %}
                        {% for filter in article.filters %}
                            <span class="badge-{{ filter.classe }} K2D-paragraph">{{ filter.name }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="article-title">
                    <h3>{{ article.brand }}</h3>
                    <p class="K2D-paragraph" id="name">{{ article.product }}</p>
                </div>
                <div class="article-description">
                    <p>{{ article.description }}</p>
                </div>
                <div class="article-footer">
                    <div class="tags">
                        {% if article.tags is not none %}
                            {% for tag in article.tags %}
                                <button>{{ tag.name }}</button>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="price">
                        {% if article.promotion_percentage is not none %}
                            <h5>{{ article.price }}€</h5>
                            <h2 id="price" class="promoted-price">{{ article.promoted_price }}€</h2>
                        {% else %}
                            <h2 id="price">{{ article.price }}€</h2>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mercadonapp/templates/home.html
{% extends '_layout.html' %}

{% set pageTemplate = 'home' %}

{% block body %}
    <body>
        <div class="home-header">
            <img class="header-img lazyload" src="{{ url_for('static', filename='img/pages/home/header.jpg') }}">
            <div class="header-presentation lazyslow-right">
                <h1 class="presentation-title">Profitez des meilleures promos</h1>
                <p class="presentation-text">Venez découvrir une liste des promotions du moment ainsi que notre catalogue complet.<br><br>Notre équipe travaille constamment à la recherche des meilleurs offres possible pour vous !<br><br>Allant de petites offres quotidiennes jusqu'aux récompenses de fidelité, nous définissons nos promotions avec vous en tête. Notre objectif est de rendre votre expérience de courses inoubliables.</p>
                <a href="{{ url_for('catalog.catalog') }}" class="presentation-btn">Toutes les promos</a>
            </div>
        </div>
    </body>
{% endblock %}

mercadonapp/templates/include/footer.html
<div class="footer">
    <div class="footer-rgpd">
        <a>Conditions d'utilisations</a>
        <a>Cookies & Données</a>
        <a>Politique de confidentialité</a>
    </div>
    <div class="footer-rgpd" id="rgpd-2">
        <a>Accessibilité</a>
        <a>Nos agriculteurs</a>
    </div>
    <div class="footer-call">
        <a href="tel:800500220">
            <img class="footer-img" src="{{ url_for('static', filename='img/footer/Phone.png') }}">
            800 500 220
        </a>
        <p class="rights">Mercadona S.A. A46103834. Tous droits reservés</p>
    </div>
    <div class="footer-social">
        <a href="https://www.facebook.com/mercadona" target="_blank"><img class="footer-img" src="{{ url_for('static', filename='img/footer/Facebook.png') }}" alt=""></a>
        <a href="https://www.instagram.com/mercadona/" target="_blank"><img class="footer-img" src="{{ url_for('static', filename='img/footer/Instagram.png') }}" alt=""></a>
        <a href="https://es.linkedin.com/company/mercadona" target="_blank"><img class="footer-img" src="{{ url_for('static', filename='img/footer/Linkedin.png') }}" alt=""></a>
        <a href="mailto:jmercadona290@gmail.com" target="_blank"><img class="footer-img" src="{{ url_for('static', filename='img/footer/Mail.png') }}" alt=""></a>
    </div>
</div>

mercadonapp/templates/include/header.html
<nav class="header navbar navbar-expand-lg navbar-light">
    <button class="header-toggler js-menu-toggler">
        <div class="header-toggler-inner" id="toggler">
            <div class="header-toggler-icon header-toggler-icon--top"></div>
            <div class="header-toggler-icon header-toggler-icon--middle"></div>
            <div class="header-toggler-icon header-toggler-icon--bottom"></div>
        </div>
    </button>
    <div class="header-menu">
        <a href="{{ url_for('catalog.catalog') }}">Catalogue</a>
        <span class="dropdown-menu--button">Rayons</span>
    </div>
    <div class="dropdown-menu hidden">
        <a class="dropdown-menu--mobile" href="{{ url_for('catalog.catalog') }}">Catalogue</a>
        <ol class="categories">
            {% for category in categories %}
                <li class="category"><a class="category-h2">{{ category.name }}</a>
                    <ul class="subcategory">
                        {% for subcategory in category.subcategories %}
                            <li><a>{{ subcategory }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ol>
        <span class="exit-dropdown">
            <img class="exit-img" src="{{ url_for('static', filename='img/header/exit.png') }}">
        </span>
    </div>
    <div class="header-logo">
        <a class="navbar-brand" href="{{ url_for('home.home') }}">
            <img src="{{ url_for('static', filename='img/header/logo.png') }}" alt="">
        </a>
    </div>
    <div class="header-search">
        <label>
            <input class="input-search" type="text" data-search>
            <img class="input-img" src="{{ url_for('static', filename='img/header/search.png') }}" alt="">
        </label>
    </div>
</nav>